
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 10 2019 21:43:51 IST (Nov 10 2019 16:13:51 UTC)

// Verification Directory fv/shiftregister 

module shiftregister(CLK, CLEAR, p_input, s_line, s_inp_l, s_inp_r,
     p_output);
  input CLK, CLEAR, s_inp_l, s_inp_r;
  input [3:0] p_input;
  input [1:0] s_line;
  output [3:0] p_output;
  wire CLK, CLEAR, s_inp_l, s_inp_r;
  wire [3:0] p_input;
  wire [1:0] s_line;
  wire [3:0] p_output;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  DFFQX1 \p_output_reg[0] (.CK (CLK), .D (n_15), .Q (p_output[0]));
  DFFQX1 \p_output_reg[1] (.CK (CLK), .D (n_14), .Q (p_output[1]));
  DFFQX1 \p_output_reg[3] (.CK (CLK), .D (n_17), .Q (p_output[3]));
  DFFQX1 \p_output_reg[2] (.CK (CLK), .D (n_16), .Q (p_output[2]));
  NAND2XL g396(.A (n_5), .B (n_4), .Y (n_17));
  NAND2XL g395(.A (n_3), .B (n_2), .Y (n_16));
  NAND2XL g397(.A (n_8), .B (n_11), .Y (n_15));
  NAND2XL g398(.A (n_12), .B (n_13), .Y (n_14));
  AOI22XL g406(.A0 (p_output[0]), .A1 (n_7), .B0 (p_output[2]), .B1
       (n_6), .Y (n_13));
  AOI22XL g400(.A0 (p_output[1]), .A1 (n_10), .B0 (n_9), .B1
       (p_input[1]), .Y (n_12));
  AOI22XL g405(.A0 (p_output[0]), .A1 (n_10), .B0 (n_9), .B1
       (p_input[0]), .Y (n_11));
  AOI22XL g401(.A0 (n_7), .A1 (s_inp_l), .B0 (p_output[1]), .B1 (n_6),
       .Y (n_8));
  AOI22XL g404(.A0 (p_output[2]), .A1 (n_7), .B0 (n_6), .B1 (s_inp_r),
       .Y (n_5));
  AOI22XL g403(.A0 (p_output[3]), .A1 (n_10), .B0 (n_9), .B1
       (p_input[3]), .Y (n_4));
  AOI22XL g402(.A0 (p_output[2]), .A1 (n_10), .B0 (n_9), .B1
       (p_input[2]), .Y (n_3));
  AOI22XL g399(.A0 (p_output[1]), .A1 (n_7), .B0 (p_output[3]), .B1
       (n_6), .Y (n_2));
  AND2X1 g408(.A (s_line[1]), .B (n_1), .Y (n_7));
  NOR2BXL g409(.AN (s_line[1]), .B (n_0), .Y (n_9));
  NOR2BXL g410(.AN (n_1), .B (s_line[1]), .Y (n_10));
  NOR2XL g407(.A (s_line[1]), .B (n_0), .Y (n_6));
  NOR2XL g411(.A (s_line[0]), .B (CLEAR), .Y (n_1));
  NAND2BXL g412(.AN (CLEAR), .B (s_line[0]), .Y (n_0));
endmodule

